name       : libavif
version    : 0.9.3
release    : 5
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.9.3.tar.gz : bcd9a1f57f982a9615eb7e2faf87236dc88eb1d0c886f3471c7440ead605060d
license    : BSD-2-Clause
component  : multimedia.library
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(rav1e)
setup      : |
    %cmake_ninja \
        -DAVIF_BUILD_TESTS=ON \
        -DAVIF_CODEC_AOM=ON \
        -DAVIF_CODEC_DAV1D=ON \
        -DAVIF_CODEC_RAV1E=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # See https://github.com/AOMediaCodec/libavif/commit/11d6725af628b116066f4bd2e5b810498c584438
    ./solusBuildDir/aviftest tests/data --io-only
