name       : libavif
version    : 0.9.0
release    : 1
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.9.0.tar.gz : ea1603fc18e7dd20cf01f0b405156576886ecb5df84db8c0e87187cd2f8a00f4
license    : BSD-2-Clause
component  : multimedia.library
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(dav1d)
    - pkgconfig(rav1e)
setup      : |
    %cmake_ninja \
        -DAVIF_BUILD_TESTS=ON \
        -DAVIF_CODEC_DAV1D=ON \
        -DAVIF_CODEC_RAV1E=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    ./solusBuildDir/aviftest tests/data
