name       : libavif
version    : 0.9.2
release    : 3
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.9.2.tar.gz : d6607d654adc40a392da83daa72a4ff802cd750c045a68131c9305639c10fc5c
license    : BSD-2-Clause
component  : multimedia.library
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(rav1e)
setup      : |
    %cmake_ninja \
        -DAVIF_BUILD_TESTS=ON \
        -DAVIF_CODEC_AOM=ON \
        -DAVIF_CODEC_DAV1D=ON \
        -DAVIF_CODEC_RAV1E=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    ./solusBuildDir/aviftest tests/data
