name       : libavif
version    : 0.11.0
release    : 9
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.11.0.tar.gz : 0c34937f5a1f2e105734dba2fc6dc4d9b12636e17964df705d3d96c5aa52667c
license    : BSD-2-Clause
component  : multimedia.library
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(rav1e)
    - gtest-devel
setup      : |
    %patch -p1 < $pkgfiles/fix_avifmetadatatest.patch
    %patch -p1 < $pkgfiles/fix_avifrgbtoyuvtest.patch
    %cmake_ninja \
        -DAVIF_BUILD_TESTS=ON \
        -DAVIF_CODEC_AOM=ON \
        -DAVIF_CODEC_DAV1D=ON \
        -DAVIF_CODEC_RAV1E=ON \
        -DAVIF_CODEC_SVT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
