name       : libavif
version    : 0.11.1
release    : 11
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.11.1.tar.gz : 0eb49965562a0e5e5de58389650d434cff32af84c34185b6c9b7b2fccae06d4e
license    : BSD-2-Clause
component  : multimedia.library
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(rav1e)
    - gtest-devel
setup      : |
    %cmake_ninja \
        -DAVIF_BUILD_TESTS=ON \
        -DAVIF_CODEC_AOM=ON \
        -DAVIF_CODEC_DAV1D=ON \
        -DAVIF_CODEC_RAV1E=ON \
        -DAVIF_CODEC_SVT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
