name       : libavif
version    : 0.10.1
release    : 8
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v0.10.1.tar.gz : 66e82854ceb84a3e542bc140a343bc90e56c68f3ecb4fff63e636c136ed9a05e
license    : BSD-2-Clause
component  : multimedia.library
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(rav1e)
setup      : |
    %cmake_ninja \
        -DAVIF_BUILD_TESTS=ON \
        -DAVIF_CODEC_AOM=ON \
        -DAVIF_CODEC_DAV1D=ON \
        -DAVIF_CODEC_RAV1E=ON \
        -DAVIF_CODEC_SVT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
